@echo off
IF NOT EXIST "%MSBUILD_EXE%" (
    echo MSBuild does not exist at "%MSBUILD_EXE%" 1>&2
    echo. 1>&2
    exit /B 1
)

IF "%MIN_WIN_NT_VERSION%"=="" SET MIN_WIN_NT_VERSION=0x0A00

IF "%MSVC_VERSION_INT%"=="14.2" (
    SET VSGEN_NAME_FULL=%VSGEN_NAME%
) ELSE (
    SET VSGEN_NAME_FULL=%VSGEN_NAME%%VSGEN_PLATFORM%
    SET VSGEN_ARCH=
)

exit /B 0

